## Call location_beam.py

In [1]:
%run location_beam.py

/home/jupyter/venv/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery.py:1936: BeamDeprecationWarning: options is deprecated since First stable release. References to <pipeline>.options will not be supported
  temp_location = pcoll.pipeline.options.view_as(
/home/jupyter/venv/lib/python3.7/site-packages/apache_beam/io/gcp/bigquery_file_loads.py:956: BeamDeprecationWarning: options is deprecated since First stable release. References to <pipeline>.options will not be supported
  temp_location = p.options.view_as(GoogleCloudOptions).temp_location

## PK verification

In [2]:
%%bigquery
select count(State) as State_Count from datamart.Location_Beam

   State_Count
0          112

In [1]:
%%bigquery
select count(distinct(State)) as State_Count from datamart.Location_Beam

   State_Count
0           56

## FK verification

In [3]:
%%bigquery
select DISTINCT(l.state) as state_fk, c.state as state_pk from datamart.Location_Beam l
right join datamart.Cases c on l.state = c.state

                    state_fk                  state_pk
0                       Guam                      Guam
1                       Iowa                      Iowa
2                       Ohio                      Ohio
3                       Utah                      Utah
4                      Idaho                     Idaho
5                      Maine                     Maine
6                      Texas                     Texas
7                     Alaska                    Alaska
8                     Hawaii                    Hawaii
9                     Kansas                    Kansas
10                    Nevada                    Nevada
11                    Oregon                    Oregon
12                   Alabama                   Alabama
13                   Arizona                   Arizona
14                   Florida                   Florida
15                   Georgia                   Georgia
16                   Indiana                   Indiana
17                   Montana                   Montana
18                   Vermont                   Vermont
19                   Wyoming                   Wyoming
20                  Arkansas                  Arkansas
21                  Colorado                  Colorado
22                  Delaware                  Delaware
23                  Illinois                  Illinois
24                  Kentucky                  Kentucky
25                  Maryland                  Maryland
26                  Michigan                  Michigan
27                  Missouri                  Missouri
28                  Nebraska                  Nebraska
29                  New York                  New York
30                  Oklahoma                  Oklahoma
31                  Virginia                  Virginia
32                 Louisiana                 Louisiana
33                 Minnesota                 Minnesota
34                      None                 Recovered
35                 Tennessee                 Tennessee
36                 Wisconsin                 Wisconsin
37                California                California
38                New Jersey                New Jersey
39                New Mexico                New Mexico
40                Washington                Washington
41               Connecticut               Connecticut
42               Mississippi               Mississippi
43               Puerto Rico               Puerto Rico
44              North Dakota              North Dakota
45              Pennsylvania              Pennsylvania
46              Rhode Island              Rhode Island
47              South Dakota              South Dakota
48             Massachusetts             Massachusetts
49             New Hampshire             New Hampshire
50             West Virginia             West Virginia
51            American Samoa            American Samoa
52                      None            Grand Princess
53            North Carolina            North Carolina
54            South Carolina            South Carolina
55            Virgin Islands            Virgin Islands
56                      None          Diamond Princess
57      District of Columbia      District of Columbia
58  Northern Mariana Islands  Northern Mariana Islands